trajectories:
  t265:
    topic: /t265/odom/sample
  legged:
    topic: /legged_odometry/pose_in_odom
  theodolite:
    topic: /theodolite_data
    type: theodolite

# Optional overrides:
# output:
#   folder: output/non-default
input: /home/seva/bags/26-07-14-slippage-test/ros2/slippage_20260714_113855.mcap
